[tool.poetry]
name = "owid-catalog"
version = "0.2.6"
description = "Core data types used by OWID for managing data."
authors = ["Our World In Data <tech@ourworldindata.org>"]
license = "MIT"
packages = [{ include = "owid" }]
readme = "README.md"
repository = "https://github.com/owid/owid-grapher-py"
homepage = "https://github.com/owid/owid-grapher-py"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.3"
jsonschema = "^3.2.0"
pandas-stubs = "^1.2.0"
dataclasses-json = "^0.5.6"
pyarrow = "^7.0.0"
ipdb = "^0.13.9"
pytest-cov = "^2.12.1"
requests = "^2.26.0"
boto3 = "^1.21.13"
Unidecode = "^1.3.4"
PyYAML = "^5.4.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^22.3"
mypy = "^0.942"
flake8 = "^3.9.2"
watchdog = "^2.1.5"
argh = "^0.26.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
